---
name: Example
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - uses: theomessin/actions-setup@main
        with:
          version: "latest"
          use-cache: true
      - id: cache
        uses: actions/cache@v3
        with:
          path: /tmp/earthly-cache
          key: earthly-cache-${{ github.run_id }}
          restore-keys: |
            earthly-cache
      - continue-on-error: true
        run: |-
          [ -d "/tmp/earthly-cache" ] && docker run --rm \
            -v earthly-cache:/volume \
            -v /tmp/earthly-cache:/filesystem \
            alpine sh -c \
            "cp -R /filesystem/* /volume/ && chmod -R 777 /volume"
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |-
          earthly --ci --push +dist
      - run: |-
          docker run --rm \
            -v earthly-cache:/volume \
            -v /tmp/earthly-cache:/filesystem \
            alpine sh -c \
            "rm -Rf /filesystem/* && cp -R /volume/* /filesystem/ && chmod -R 777 /filesystem"
